FROM gcr.io/deeplearning-platform-release/tf-gpu:latest
RUN conda create -n python-3.9
RUN conda install -n python-3.9 ipykernel python=3.9 
#SHELL ["/bin/bash", "-c"]
#RUN source /opt/conda/bin/activate /opt/conda/envs/python-3.9 && python -m ipykernel install --user --name=python-3.9 && conda deactivate
